app/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_view
from .forms import LoginForm, MyPasswordChangeForm, MyPasswordResetForm, MySetPasswordForm

urlpatterns = [
    path("", views.home, name="home"),
    path('about/', views.about, name="about"),
    path('contact/', views.contact, name="contact"),
    path("category/<slug:val>", views.CategoryView.as_view(),name="category"),
    path("category-title/<val>", views.CategoryTitle.as_view(),name="category-title"),
    path("product-detail/<int:pk>", views.ProductDetail.as_view(),name="product-detail"),
    path('profile/', views.ProfileView.as_view(), name='profile'),
    path('address/', views.address, name='address'),

    path('add-to-cart/', views.add_to_cart, name='add_to_cart'),
    path('cart/', views.show_cart, name='showcart'),
    path('checkout/', views.checkout.as_view(), name='checkout'),
    path('orders/', views.orders, name='orders'),

    path('payment/', views.payment_page, name='payment_page'),
    path('process_payment/', views.process_payment, name='process_payment'),

    #path('checkout/', views.show_cart, name='showcart'),
    path('pluscart/', views.plus_cart),
    path('minuscart/', views.minus_cart),
    path('removecart/', views.remove_cart),
    
    

    #login authentication
    path('registration/', views.CustomerRegistrationView.as_view(), name='customerregistration'),
    path('accounts/login/', auth_view.LoginView.as_view(template_name='app/login.html', authentication_form=LoginForm) , name='login'),
    path('passwordchange/', auth_view.PasswordChangeView.as_view( # type: ignore
        template_name='app/passwordchange.html',
        success_url='/passwordchangedone/'
    ), name='passwordchange'),
    path('passwordchangedone/', auth_view.PasswordChangeDoneView.as_view( # type: ignore
        template_name='app/passwordchangedone.html'
    ), name='passwordchangedone'),

    path('logout/', auth_view.LogoutView.as_view(next_page='login'), name='logout'),
    

    path('password-reset/', auth_view.PasswordResetView.as_view(template_name='app/password_reset.html', form_class=MyPasswordResetForm), name='password_reset'),
    path('password-reset/done/', auth_view.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_view.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html', form_class=MySetPasswordForm), name='password_reset_confirm'),
    path('password-reset-complete/', auth_view.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'),


    


]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecom/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("app.urls")),
]

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, UsernameField, PasswordChangeForm, SetPasswordForm, PasswordResetForm 
from django.contrib.auth.models import User

from .models import Customer


class LoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={'autofocus ':'True','class':'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-control'}))

class CustomerRegistrationForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'autofocus': 'True'}))
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    password2 = forms.CharField(label=' Confirm Password', widget=forms.PasswordInput(attrs={'class':'form-control'}))
    
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

class MyPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label= 'Old Password', widget=forms.PasswordInput(attrs={'autofocus':'True','autocomplete':'current-password','class':'form-Control'}))
    new_password1 = forms.CharField(label= 'New Password', widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-Control'}))
    new_password2 = forms.CharField(label= 'Confirm Password', widget=forms.PasswordInput(attrs={'autocomplete':'current-password','class':'form-Control'}))


class MyPasswordResetForm(PasswordResetForm):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control'}))

def __init__(self, *args, **kwargs):
        # Remove the 'user' argument if passed and not needed
        kwargs.pop('user', None)
        super().__init__(*args, **kwargs)


class MySetPasswordForm(SetPasswordForm):
    new_password1 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        strip=False
    )
    new_password2 = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'autocomplete': 'new-password'}),
        strip=False
    )
#class MySetPasswordForm(SetPasswordForm):
#    new_password1 = forms.CharField(
#        label='New Password',
#        widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'})
#    )
#    new_password2 = forms.CharField(
#        label='Confirm New Password',
#        widget=forms.PasswordInput(attrs={'autocomplete':'current-password', 'class':'form-control'})
#    )

class CustomerProfileForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['name','locality','city','mobile','state','zipcode']
        widgets={
            'name':forms.TextInput(attrs={'class':'from-control'}),
            'locality':forms.TextInput(attrs={'class':'from-control'}),
            'city':forms.TextInput(attrs={'class':'from-control'}),
            'mobile':forms.NumberInput(attrs={'class':'from-control'}),
            'state':forms.Select(attrs={'class':'from-control'}),
            'zipcode':forms.NumberInput(attrs={'class':'from-control'}),
        }

app/templates/app/about.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}About{% endblock title %}

{% block banner-slider %}
<div id="carouselBanner" class="carousel slide" data-bs-ride="carousel" data-bs-interval="2000">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{% static 'app/images/banner/b1.jpg' %}" class="d-block w-100" alt="banner">
    </div>
    <div class="carousel-item">
      <img src="{% static 'app/images/banner/b2.jpg' %}" class="d-block w-100" alt="banner">
    </div>
    <div class="carousel-item">
      <img src="{% static 'app/images/banner/b3.jpg' %}" class="d-block w-100" alt="banner">
    </div>
    <div class="carousel-item">
      <img src="{% static 'app/images/banner/b4.jpg' %}" class="d-block w-100" alt="banner">
    </div>
  </div>
</div>
{% endblock banner-slider %}

{% block main-content %}
<div class="container mt-3">
    <br>
    <h2 class="text-center">About Us</h2>
    <br>
    <div class="row container">
        <p class="fs-4 text-center">This is a  public limited company having its registered and corporate office at Satara City of Maharashtra State in India. The company was incorporated in the year 2022 and production commenced in 2024. This is one of the fastest growing Public Listed Companies in Satara</p>
    </div>
     
      <br><br>
    <h2 class="text-center">Mission</h2>
    <br>
    <div class="row container">
        <p class="fs-4 text-center">To embrace the right technology to delight our Customers Empowering the farmer coummunity through our unique 'Relationship Farming' Model To anticipate, understand and respond to our Customers needs by creating high-quality products and making them available through innovative and convenient channels
        </p>
    </div>
</div>
<br><br>
{% endblock main-content %}

app/templates/app/addtocart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}

{% block main-content %}
<div class="container my-5">
    <div class="row">
        {% if cart %}
        <h1 class="text-center mb-5">Shopping Cart</h1>
        <div class="col-sm-8">
            <div class="card">
                <div class="card-body">
                    <h3>Cart</h3>
                    {% for item in cart %}
                    <div class="row">
                        <div class="col-sm-3 text-center align-self-center">
                            <img src="{{ item.product.product_image.url }}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150">
                        </div>
                        <div class="col-sm-9">
                            <div>
                                <h5>{{ item.product.title }}</h5>
                                <p class="mb-2 text-muted small">{{ item.product.description }}</p>
                                <div class="my-3">
                                    <label for="quantity">Quantity</label>
                                    <a class="minus-cart btn" pid="{{ item.product.id }}"><i class="fas fa-minus-square fa-lg"></i></a>
                                    <span id="quantity">{{ item.quantity }}</span>
                                    <a class="plus-cart btn" pid="{{ item.product.id }}"><i class="fas fa-plus-square fa-lg"></i></a>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <a href="#" class="remove-cart btn btn-sm btn-secondary mr-3" pid="{{ item.product.id }}">Remove item</a>
                                    <p class="mb-0"><span><strong>Rs. {{ item.product.discounted_price }}</strong></span></p>
                                </div>
                            </div>
                        </div>
                    </div>
                    <hr class="text-muted">
                    {% endfor %}
                </div>
            </div>
        </div>

        <div class="col-sm-4">
            <div class="card">
                <div class="card-body">
                    <h3>The Total Amount of</h3>
                    <ul class="list-group">
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">
                            Amount<span id="amount">Rs. {{ amount }}</span>
                        </li>
                        <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs. 40.00</span></li>
                        <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
                            <div>
                                <strong>Total</strong> <small>{including GST}</small>
                            </div>
                            <span id="totalamount"><strong>Rs. {{ totalamount|floatformat:2 }}</strong></span>
                        </li>
                            
                    </ul>
                    <div class="d-grid">
                        <a href="{% url 'checkout' %}" class="btn btn-primary">Place Order</a>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
        <h1 class="text-center mb-5">Cart is Empty</h1>
        {% endif %}
    </div>
</div>
{% endblock main-content %}

app/templates/app/base.html
<!DOCTYPE html>
{% load static %} 
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE-edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}" />
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}" />

    <title> Dairy Products | {% block title %}{% endblock title %}</title>
</head>
<body>
   
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #005f73;">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">
            <img src="{% static 'app/images/Neel.png' %}" width="70" height="70" />
          </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Products
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="{% url 'category' 'ML' %}">Milk</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'CR' %}">Curd</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'MS' %}">Milkshake</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'LS' %}">Lassi</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'GH' %}">Ghee</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'PN' %}">Paneer</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'CZ' %}">Cheese</a></li>
                  <li><a class="dropdown-item" href="{% url 'category' 'IC' %}">Ice-Cream</a></li>
                </ul>
              </li>
              <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'about' %}">About Us</a>
            </li>
            <li class="nav-item">
                <a class="nav-link text-white" href="{% url 'contact' %}">Contact Us</a>
            </li>
              
            </ul>
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-light" type="submit">Search</button>
            </form>
          </div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown mx-2">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">Revati</a>
                <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                  <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li>
                  <li><a class="dropdown-item" href="{% url 'orders' %}">Orders</a></li>
                  <li><a class="dropdown-item" href="{% url 'passwordchange' %}">Change Password</a></li>
                  <li>
                    <form method="POST" action="{% url 'logout' %}" style="margin: 0; padding: 0;">
                        {% csrf_token %}
                        <button type="submit" class="dropdown-item" style="background: none; border: none; width: 100%; text-align: left; padding: .25rem 1.5rem;">
                            Logout
                        </button>
                    </form>
                </li>
                  <!--li>
                    <form method="POST" action="{% url 'logout' %}" style="margin: 0; padding: 0;">
                        {% csrf_token %}
                        <a href="#" onclick="this.closest('form').submit(); return false;" class="dropdown-item" style="display: block; width: 100%; text-align: left; padding: .25rem 1.5rem; background: none; border: none; text-decoration: none;">
                            Logout
                        </a>
                    </form>
                </li-->
                

                </ul>
            </li>
            <li class="nav-item mx-2">
                <a href="{% url 'showcart' %}" class="nav-link text-white">Cart 4</a>
            </li>
            <li class="nav-item mx-2">
                <a href="#" class="nav-link text-white">Wishlist 4</a>
            </li>
            {% else %}
            <li class="nav-item mx-2">
                <a href="{% url 'login' %}" class="nav-link text-white">Login</a>
            </li>
            <li class="nav-item mx-2">
                <a href="{% url 'customerregistration' %}" class="nav-link text-white">Registration</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>

      {% block banner-slider %}{% endblock banner-slider %}
      {% block information %}{% endblock information %}
      {% block main-content %}{% endblock main-content %}
      {% block payment-gateway %}{% endblock payment-gateway %}

      <footer class="footer" style="background-color: #005f73; padding: 20px 0; display: flex; align-items: center; justify-content: center; height: 40px; position: fixed; bottom: 0; width: 100%;">
        <p class="text-white m-0">Copyright : 2024 || Developed by : Revati Pandit</p>
      </footer>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js"></script>

    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/all.min.js' %}"></script>
    <script src="{% static 'app/js/myscript.js' %}"></script>



</body>
</html>

app/templates/app/category.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Category{% endblock title %}

{% block main-content %}
    <div class="container my-5">
        <div class="row">
            <div class="col-sm-3">
                <div class="list-group">
                    {% for val in title %}
                        <a href="{% url 'category-title' val.title %}" class="list-group-item list-group-item-action" aria-current="true">
                            {{val.title}}</a>
                    {% endfor %}
                </div>
            </div>
            <div class="col-sm-9">
                <div class="row">
                    {% for prod in product %}
                    <div class="col text-center mb-4">
                        <a href="{% url 'product-detail' prod.id %}" class="btn">
                        <div>
                            <img src="{{prod.product_image.url}}" width="300px" height="200px" />
                            <div class="fw-bold">{{prod.title}}</div>
                            <div class="fw-bold text-danger">
                                RS.{{prod.discounted_price}}/-
                                <small class="fw-light text-decoration-line-through">{{prod.selling_price}}</small>
                            </div> 
                        </div>
                        </a>
                    </div>
                    {% endfor in %}
                </div>
            </div>
        </div>
    </div>
{% endblock main-content %}

app/templates/app/checkout.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}

{% block main-content %}
<div class="container">  
    <!-- Existing content... -->
    <div class="row mt-5">
        <div class="col-sm-6">
            <!-- Existing content... -->
            <p class="fw-bold">Total Cost + Rs. 40 = {{ totalamount }}</p>
            <small>Terms and Conditions: Lorem ipsum dolor sit amet, consectetur adipisicing elit. Mollitia, ullam saepe! Iure optio repellat dolor velit, minus rem, facilis quoque neque laboriosam adipisci nisi nihil in et quite.</small>
        </div>
        <div class="col-sm-5 ms-auto">  
            <h4>Select Shipping Address</h4>
            <hr>
            <form method="post" id="address-form">
                {% csrf_token %}
                {% for ad in add %}
                <div class="card mb-2">
                    <div class="card-body">
                        <h5>{{ ad.name }}</h5>  
                        <p>Mobile: {{ ad.mobile }}</p>
                        <p>{{ ad.locality }} {{ ad.city }} {{ ad.state }}. {{ ad.zipcode }}</p> 
                    </div>
                </div>
                <div class="form-check mt-2 mb-5">
                    <input class="form-check-input" type="radio" name="custid" id="custadd{{ forloop.counter }}" value="{{ ad.id }}">
                    <label class="form-check-label fw-bold" for="custadd{{ forloop.counter }}">
                        Address: {{ forloop.counter }}</label>
                </div>
                {% endfor %}
                <div class="form-check mb-3">
                    <label for="totalamount" class="form-label">Total Amount</label>
                    <input type="number" class="form-control" name="totalamount" value="{{ totalamount }}" readonly>
                </div>
                <div class="text-end">
                    <a href="{% url 'payment_page' %}" class="btn btn-warning mt-3 fw-bold">Payment</a>
                </div>
                
            </form>
        </div>
    </div>
</div>

{% endblock main-content %}



app/templates/app/customerregistration.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Customer Registration{% endblock title %}

{% block main-content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Customer Registration</h3>
            <hr>

            <form action="" method="post" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for fm in form %}
                    {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.errors|striptags}}</small>
                    <br>
                {% endfor %}
                <input type="submit" value="Register" class="btn btn-primary">
                <br>

                <div class="text-center text-primary fw-bold">
                    <small>Existing User ? <a href="{% url 'login' %}" class="text-danger">Login Now</a></small>
                </div>

                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{error}}</p>
                    {% endfor %}
                {% endif %} 

                {% if messages %}
                {% for msg in messages %}
                    <div class="alert alert-{{msg.tags}}" role="alert">
                        {{msg}}
                    </div>
                {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block main-content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Login</h3>
            <hr>
            <form action="" method="POST" novalidate class="shadow p-5">
                {% csrf_token %}
                {% for field in form %}
                    <div class="mb-3">
                        {{ field.label_tag }}
                        {{ field }}
                        <small class="text-danger">{{ field.errors|striptags }}</small>
                    </div>
                {% endfor %}

                <small>
                    <a href="{% url 'password_reset' %}">Forgot Password ?</a>
                </small>
                <br>
                <button type="submit" class="btn btn-primary mt-4">Login</button>
                <div class="text-center text-primary fw-bold mt-3">
                    <small>New User? <a href="{% url 'customerregistration' %}" class="text-danger">Create an Account</a></small>
                </div>
                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}

app/templates/app/orders.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Orders{% endblock %}

{% block main-content %}
<div class="container my-5">
    <div class="row">
        <h3>Welcome </h3><span class="text-capitalize">{{ request.user.username }}</span>
        
        <div class="col-sm-2 border-end">
            <ul class="list-unstyled">
                <li class="d-grid"><a href="{% url 'orders' %}" class="btn btn-primary">Orders</a></li>
            </ul>
        </div>

        <div class="col-sm-9 offset-sm-1">
            {% for op in order_placed %}
            <div class="row mb-3">
                <div class="col-sm-2">
                    <img src="{{ op.product.product_image.url }}" class="img-fluid" height="100" width="100" alt="Product Image"/>
                </div>
                <div class="col-sm-7">
                    <p>Product: {{ op.product.title }}</p>
                    <p>Quantity: {{ op.quantity }}</p>
                    <p>Price: {{ op.product.price }}</p>
                </div>
                <div class="col-sm-3">
                    <p>Order Status: {{ op.status }}</p>
                    {% if op.status == 'Accepted' %}
                    <div class="progress">
                        <div class="progress-bar bg-primary" role="progressbar" style="width: 20%;" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% elif op.status == 'Packed' %}
                    <div class="progress">
                        <div class="progress-bar bg-info" role="progressbar" style="width: 40%;" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% elif op.status == 'On the Way' %}
                    <div class="progress">
                        <div class="progress-bar bg-warning" role="progressbar" style="width: 60%;" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% elif op.status == 'Delivered' %}
                    <div class="progress">
                        <div class="progress-bar bg-success" role="progressbar" style="width: 100%;" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% elif op.status == 'Cancel' %}
                    <div class="progress">
                        <div class="progress-bar bg-danger" role="progressbar" style="width: 0%;" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100"></div>
                    </div>
                    {% endif %}
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/password_reset.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}

{% block main-content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Reset Password</h3>
            <hr>
            <form action="" method="POST" novalidate class="shadow p-5">
                {% csrf_token %}
                
                {% for fm in form %}
                    <div class="mb-3">
                        {{ fm.label_tag }}
                        {{ fm }}
                        <small class="text-danger">{{ fm.errors|striptags }}</small>
                    </div>
                {% endfor %}

                <button type="submit" class="btn btn-primary mt-4">Submit</button>

                {% if form.non_field_errors %}
                    <div class="alert alert-danger my-3">
                        {% for error in form.non_field_errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}

app/templates/app/passwordchange.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Change Password{% endblock title %}

{% block main-content %}
<div class="container">
    <div class="row my-3">
        <div class="col-sm-6 offset-sm-3">
            <h3>Change Password</h3>
            <hr>
            <form action="" method="POST" novalidate class="shadow p-5">
                {% csrf_token %}

                <div class="mb-3">
                    {{ form.old_password.label_tag }}
                    <input type="password" name="old_password" id="id_old_password" class="form-control form-control-lg" value="{{ form.old_password.value|default_if_none:'' }}">
                    <small class="text-danger">{{ form.old_password.errors|striptags }}</small>
                </div>

                <div class="mb-3">
                    {{ form.new_password1.label_tag }}
                    <input type="password" name="new_password1" id="id_new_password1" class="form-control form-control-lg" value="{{ form.new_password1.value|default_if_none:'' }}">
                    <small class="text-danger">{{ form.new_password1.errors|striptags }}</small>
                </div>

                <div class="mb-3">
                    {{ form.new_password2.label_tag }}
                    <input type="password" name="new_password2" id="id_new_password2" class="form-control form-control-lg" value="{{ form.new_password2.value|default_if_none:'' }}">
                    <small class="text-danger">{{ form.new_password2.errors|striptags }}</small>
                </div>

                <input type="submit" class="btn btn-primary mt-4" value="Change Password">

                {% if form.non_field_errors %}
                    {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{ error }}</p>
                    {% endfor %}
                {% endif %}
            </form>
        </div>
    </div>
</div>
{% endblock main-content %}